-- 0005 — observations (hypertable)
--
-- One row per attempt, INCLUDING attempts that produced nothing. A null result is
-- data (GLOSSARY.md).


-- The public identifier MSP §4.4's acknowledgement returns (D-027). A function
-- rather than an inline expression for two reasons: a generated column requires
-- an immutable expression, and the store layer needs to call this to answer a
-- retry without reading the row back.
--
-- IMMUTABLE is a promise, and it is worth stating why it holds. convert_to() is
-- marked STABLE rather than IMMUTABLE because a text-to-bytes conversion depends
-- on the server encoding in the general case. Both inputs here are generated by
-- the platform — an assignment id we minted and an integer — so they are always
-- ASCII, and every server encoding PostgreSQL supports is ASCII-compatible. The
-- bytes are therefore identical under any of them.
--
-- The obvious alternative, casting text to bytea directly, is WRONG: that cast
-- routes through bytea_in, so an id containing a backslash would be read as an
-- escape sequence. 'as\x41' would hash as 'asA'.
create function observation_id(assignment_id text, revision integer)
returns text
language sql
immutable
strict
parallel safe
as $$
    select 'ob_' || substr(
        encode(sha256(convert_to($1 || ':' || $2::text, 'UTF8')), 'hex'), 1, 12)
$$;

comment on function observation_id(text, integer) is
    'Public observation identifier, derived so an idempotent retry returns the '
    'same id as the original submission. See docs/DECISIONS.md D-027.';

create table observations (
    -- Natural key. A resubmission appends revision + 1 rather than overwriting
    -- (D-015); the highest revision is current. Chosen over a supersedes_id
    -- pointer because it orders the lineage without a chain walk, and this key
    -- has to exist as the primary key regardless.
    assignment_id       text        not null,
    revision            integer     not null default 1,

    -- Derived, not allocated: an idempotent retry must return the SAME id as the
    -- original submission, and D-015 makes that the path on which nothing is
    -- written — so it must not require reading the row back to answer. Generated
    -- in the database rather than in Python so the ingest path and the public
    -- API cannot drift apart. See the function definition above.
    observation_id      text        generated always as (
                            observation_id(assignment_id, revision)
                        ) stored,

    -- The partition column. Analysis needs started_at, so it is partitioned on
    -- rather than received_at — but ingest rejects a started_at outside
    -- [now - 30 days, now + 1 hour] as `malformed` (D-013), because a station
    -- with a dead clock would otherwise place a chunk in 1970 that every
    -- retention and compression policy then mishandles forever.
    started_at          timestamptz not null,
    ended_at            timestamptz not null,

    station_id          text        not null references stations (station_id),
    satellite_id        text        not null references satellites (satellite_id),

    -- Pinned to the MSP §4.4 enum (D-010). MSP-SPEC.md is the authority; this
    -- restates the values, it does not define them.
    --
    -- `no_signal` and `not_attempted` must NEVER be conflated: the first is data
    -- (the station was verifiably listening and heard nothing), the second is an
    -- operational failure. Neither is a decline, which produces no row here at
    -- all and appears as assignments.state = 'expired'.
    outcome             text        not null
                                    check (outcome in ('decoded', 'signal_no_decode',
                                                       'no_signal', 'aborted', 'not_attempted')),

    signal_detected     boolean     not null default false,
    -- first_detection_at minus predicted AOS is the timing-error measurement,
    -- which is the project's primary measurement of orbital data quality.
    first_detection_at  timestamptz,
    peak_snr_db         double precision,
    doppler_samples     jsonb,

    -- Metadata only until O-1 is resolved and the products table exists (D-018).
    -- Stored verbatim so nothing a station sends is lost in the meantime.
    products_json       jsonb       not null default '[]'::jsonb,
    client_notes        text,

    -- Copied from the station's registry record, never read from the payload:
    -- station input is untrusted and provenance is the last field to take on
    -- trust (D-013).
    simulated           boolean     not null default false,
    provenance          text        not null default 'station'
                                    check (provenance in ('station', 'archive', 'manual')),

    -- MSP §6: queued observations are submitted with their ORIGINAL timestamps
    -- and the platform records submission delay separately. That delay is
    -- submitted_at - ended_at, which is why both are stored.
    submitted_at        timestamptz not null default now(),

    -- A byte-identical resubmission — the queued-retry case of MSP §6 — returns
    -- the existing revision and writes nothing. Only a changed body appends.
    content_sha256      bytea       not null,

    -- Timescale requires the partitioning column in every unique key, which is
    -- why started_at appears here (D-013).
    constraint observations_pkey primary key (assignment_id, revision, started_at),
    constraint observation_window_ordered check (started_at <= ended_at),
    constraint observation_detection_consistent check (
        (signal_detected and first_detection_at is not null)
        or (not signal_detected and first_detection_at is null)
    )
);

select create_hypertable('observations', by_range('started_at', interval '7 days'));

create index observations_station_started_idx on observations (station_id, started_at desc);
create index observations_satellite_started_idx on observations (satellite_id, started_at desc);

-- The public API looks observations up by the id it handed out. Not unique:
-- a unique index on a hypertable must include the partitioning column, and
-- observation_id is already unique by construction over (assignment_id, revision).
create index observations_observation_id_idx on observations (observation_id);

alter table observations set (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'station_id',
    timescaledb.compress_orderby = 'started_at desc'
);
select add_compression_policy('observations', interval '7 days');

-- No retention policy. DATA-MODEL.md says "90 days then downsampled" — dropping
-- chunks before the continuous aggregate that downsamples them exists is just
-- data loss on a timer. Retention lands in Phase 3 with the aggregate.


-- The current observation per assignment. A station that resubmits sees one row
-- here and no duplicate, so MSP §6's idempotency requirement is satisfied while
-- the earlier report survives underneath.
create view observations_current as
select distinct on (assignment_id) *
from observations
order by assignment_id, revision desc;

comment on view observations_current is
    'Latest revision per assignment. Query this, not observations, unless you '
    'specifically want the correction history.';
