"""One round of scheduled work, and the loop that repeats it.

A round generates passes over ``[now, now + horizon)`` and then schedules them
under configuration A (D-110). Both steps are idempotent over a horizon (D-063,
D-066), so consecutive rounds overlap without writing anything twice, and a round
that is interrupted leaves nothing the next one cannot finish.

**A failed task is recorded and the process carries on.** Scheduling still runs
after pass generation fails, because it schedules passes already stored and a
horizon generated by the previous round is still worth using. Neither failure
ends the loop: a database restarting for a minute must cost a round or two, not
the scheduler.

**Stopping is prompt.** The wait between rounds is an ``Event``, so SIGTERM ends
it at once; a task already running is allowed to finish its transaction.

Reference: docs/DECISIONS.md D-063, D-066, D-110.
"""

from __future__ import annotations

import logging
import threading
import time
from collections.abc import Callable
from contextlib import AbstractContextManager
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Protocol, TypeVar

from meridian.jobs.job_metrics import (
    LAST_SUCCESS,
    PASS_GENERATION,
    PASSES_COMPUTED,
    SCHEDULE,
    SCHEDULER_CANDIDATES,
    TASK_DURATION,
    TASK_FAILURES,
)
from meridian.orbit.service import OrbitService
from meridian.pass_generation import (
    GenerationHorizon,
    GenerationReport,
    generate_passes,
)
from meridian.scheduler.run import ScheduleReport, ScheduleRequest, run_schedule
from meridian.store.stations import Connection

__all__ = [
    "DatabaseRoundWork",
    "RoundOutcome",
    "RoundPlan",
    "RoundWork",
    "run_round",
    "run_until_stopped",
]

_log = logging.getLogger(__name__)

_Report = TypeVar("_Report")


@dataclass(frozen=True, slots=True)
class RoundPlan:
    """What every round does, fixed for the life of the process."""

    horizon: timedelta
    model_config: str
    turnaround_s: float


class RoundWork(Protocol):
    """The two tasks a round runs; a stub stands in for them in tests."""

    def generate(self, horizon: GenerationHorizon) -> GenerationReport:
        """Generate and store passes over ``horizon``."""
        ...

    def schedule(self, request: ScheduleRequest) -> ScheduleReport:
        """Schedule the stored passes ``request`` describes."""
        ...


class DatabaseRoundWork:
    """The real tasks: each opens its own connection, commits and closes it."""

    def __init__(
        self,
        connect: Callable[[], AbstractContextManager[Connection]],
        orbit: OrbitService,
    ) -> None:
        """Bind the tasks to a way of connecting and one propagator.

        Args:
            connect: Returns a connection as a context manager that commits on
                a clean exit — ``psycopg.connect(...)`` itself, in production.
            orbit: Built once for the process; building it parses a
                leap-second table.
        """
        self._connect = connect
        self._orbit = orbit

    def generate(self, horizon: GenerationHorizon) -> GenerationReport:
        """Run ``meridian.pass_generation`` exactly as the CLI does."""
        with self._connect() as conn:
            return generate_passes(conn, self._orbit, horizon)

    def schedule(self, request: ScheduleRequest) -> ScheduleReport:
        """Run ``meridian.scheduler`` exactly as the CLI does."""
        with self._connect() as conn:
            return run_schedule(conn, self._orbit, request)


@dataclass(frozen=True, slots=True)
class RoundOutcome:
    """Which tasks of one round completed."""

    generated: GenerationReport | None
    scheduled: ScheduleReport | None


def _timed(task: str, action: Callable[[], _Report]) -> _Report | None:
    """Run one task, recording its duration and its success or failure.

    The catch is deliberately broad. This is the supervisor of long-running
    work: a task's failure of any kind is logged with its traceback and counted,
    and the loop goes on — which is what ``except Exception`` is for, and the
    only place in the platform it is.
    """
    started = time.perf_counter()
    try:
        result = action()
    except Exception:
        TASK_FAILURES.labels(task=task).inc()
        _log.exception("%s failed; the next round will try again", task)
        return None
    finally:
        TASK_DURATION.labels(task=task).observe(time.perf_counter() - started)
    LAST_SUCCESS.labels(task=task).set(time.time())
    return result


def run_round(work: RoundWork, plan: RoundPlan, now: datetime) -> RoundOutcome:
    """Generate passes from ``now``, then schedule them.

    Args:
        work: The two tasks.
        plan: The horizon, configuration and turnaround every round uses.
        now: The round's start, timezone-aware UTC; both tasks cover
            ``[now, now + plan.horizon)``.

    Returns:
        Each task's report, or ``None`` for a task that failed.
    """
    end = now + plan.horizon
    generated = _timed(
        PASS_GENERATION, lambda: work.generate(GenerationHorizon(start=now, end=end))
    )
    if generated is not None:
        PASSES_COMPUTED.set(generated.passes_computed)
        _log.info(
            "generated %d passes, stored %d",
            generated.passes_computed,
            generated.passes_stored,
        )

    request = ScheduleRequest(
        start=now,
        end=end,
        model_config=plan.model_config,
        turnaround_s=plan.turnaround_s,
    )
    scheduled = _timed(SCHEDULE, lambda: work.schedule(request))
    if scheduled is not None:
        SCHEDULER_CANDIDATES.set(scheduled.candidates_considered)
        _log.info(
            "scheduled %d and skipped %d of %d candidates, %d rows written",
            scheduled.scheduled,
            scheduled.skipped,
            scheduled.candidates_considered,
            scheduled.rows_written,
        )
    return RoundOutcome(generated=generated, scheduled=scheduled)


def run_until_stopped(
    round_once: Callable[[], object], interval_s: float, stop: threading.Event
) -> int:
    """Run rounds every ``interval_s`` seconds until ``stop`` is set.

    Args:
        round_once: Runs one round; its result is not used here.
        interval_s: Seconds from the end of one round to the start of the next.
        stop: Set by the signal handler; ends the wait at once.

    Returns:
        How many rounds ran, which tests use to prove the loop stopped.
    """
    rounds = 0
    while not stop.is_set():
        round_once()
        rounds += 1
        stop.wait(interval_s)
    return rounds
