"""Stations as archives publish them — never rows in ``stations``.

Reads and writes ``archive_stations``
(``deploy/migrations/sql/0016_archive_ingest.sql``). A row here describes a
station somebody else operates, as some archive described it: a key, perhaps a
name, perhaps a published location, perhaps a declared capability.

**Not the registry.** ``stations`` holds stations that registered, hold a bearer
token and send heartbeats, and every reliability figure we publish is computed
from rows whose listening evidence we therefore have. Nothing here has any of
that, which is why it is a separate table rather than a flag on that one
(D-139).

**Content-keyed, as ``element_sets`` is.** A station whose published coordinates
change becomes a new row rather than silently rewriting every completeness
denominator already computed from the old ones (D-057's argument, applied to
somebody else's data).

**Why the location matters here at all.** Stage 16's completeness ratio is
observed over geometrically available, and the denominator is ours — computed
by our own orbit service from this station's published position, never taken
from the archive. :func:`count_denominator_inputs` exists so that the stations
we *cannot* compute one for are counted and published rather than quietly
dropped, which would be this project's own methodological threat arriving
through the back door.

Reference: docs/DATA-MODEL.md; docs/DECISIONS.md D-139.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime

from psycopg.rows import class_row

from meridian.store.stations import Connection

__all__ = [
    "ArchiveStationArrival",
    "NewArchiveStation",
    "StoredArchiveStation",
    "count_denominator_inputs",
    "find_archive_station_by_id",
    "find_archive_stations_for_source",
    "insert_archive_station",
]


@dataclass(frozen=True, slots=True)
class NewArchiveStation:
    """One archive station in insertable form.

    ``denominator_inputs`` is absent because it is a generated column: the
    database derives it from the location and capability, so no caller can
    supply a value that disagrees with them — the same reasoning
    ``NewElementSet`` applies to ``content_sha256``.
    """

    record_id: int
    """The artefact this description was read out of."""

    source_id: str
    source_station_key: str
    """The archive's own key for the station, verbatim."""

    content_sha256: bytes
    """Of this description's canonical form.

    Part of the key, so a station whose published details change is a new row.
    """

    name: str | None = None
    lat_deg: float | None = None
    lon_deg: float | None = None
    """Published, not measured, and frequently absent.

    Many archives publish a grid square or nothing at all. Stored as a pair or
    not at all — a latitude without a longitude is not a place, and would be
    used as one.
    """

    alt_m: float | None = None
    capability: dict[str, object] | None = None
    """What the archive says the station can receive, in the archive's shape."""


@dataclass(frozen=True, slots=True)
class StoredArchiveStation:
    """One row of ``archive_stations`` as read back."""

    archive_station_id: int
    record_id: int
    source_id: str
    source_station_key: str
    name: str | None
    lat_deg: float | None
    lon_deg: float | None
    alt_m: float | None
    capability: dict[str, object] | None
    content_sha256: bytes
    denominator_inputs: str
    """``neither``, ``location_only`` or ``location_and_capability``.

    Generated by the database. What Stage 16 can actually compute for this
    station, so the shortfall is a number rather than a silence.
    """

    first_seen_at: datetime


@dataclass(frozen=True, slots=True)
class ArchiveStationArrival:
    """The stored id, and whether this call was what wrote it."""

    archive_station_id: int
    written: bool


@dataclass(frozen=True, slots=True)
class _StationId:
    """One id, so it comes back typed rather than cast from ``object``."""

    archive_station_id: int


@dataclass(frozen=True, slots=True)
class _InputsCount:
    """One ``denominator_inputs`` value and how many stations have it."""

    denominator_inputs: str
    station_count: int


def insert_archive_station(
    conn: Connection, station: NewArchiveStation
) -> ArchiveStationArrival:
    """Store one archive station, or return the id this description already has.

    Args:
        conn: An open connection.
        station: The station as the archive described it.

    Returns:
        The stored id, and whether this call wrote it.

    Note:
        Keyed on ``(source_id, source_station_key, content_sha256)``, so the
        same description loaded twice is one row and a *changed* description is
        a second one. The old row stays exactly as it was, because a
        denominator computed from it last month has to stay explainable this
        month.
    """
    with (
        conn.transaction(),
        conn.cursor(row_factory=class_row(_StationId)) as cur,
    ):
        cur.execute(
            """
            insert into archive_stations (record_id, source_id, source_station_key,
                                          name, lat_deg, lon_deg, alt_m,
                                          capability_json, content_sha256)
            values (%s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s)
            on conflict on constraint archive_station_unique do nothing
            returning archive_station_id
            """,
            (
                station.record_id,
                station.source_id,
                station.source_station_key,
                station.name,
                station.lat_deg,
                station.lon_deg,
                station.alt_m,
                None
                if station.capability is None
                else json.dumps(station.capability, sort_keys=True),
                station.content_sha256,
            ),
        )
        inserted = cur.fetchone()
        if inserted is not None:
            return ArchiveStationArrival(
                archive_station_id=inserted.archive_station_id, written=True
            )

        cur.execute(
            """
            select archive_station_id from archive_stations
            where source_id = %s and source_station_key = %s
              and content_sha256 = %s
            """,
            (station.source_id, station.source_station_key, station.content_sha256),
        )
        existing = cur.fetchone()
        if existing is None:  # pragma: no cover — the conflict proves the row
            message = "insert conflicted but the conflicting row is not readable"
            raise RuntimeError(message)
        return ArchiveStationArrival(
            archive_station_id=existing.archive_station_id, written=False
        )


def find_archive_station_by_id(
    conn: Connection, archive_station_id: int
) -> StoredArchiveStation | None:
    """The archive station with this id.

    Args:
        conn: An open connection. Read-only; opens no transaction of its own.
        archive_station_id: The id a stored reception recorded.

    Returns:
        The station, or None when no such row exists.

    Note:
        ``capability_json`` is selected under an alias, because the field holds
        decoded objects rather than the text the column name promises — the
        same treatment ``station_capabilities.horizon_mask`` already gets.
    """
    with conn.cursor(row_factory=class_row(StoredArchiveStation)) as cur:
        cur.execute(
            """
            select archive_station_id, record_id, source_id, source_station_key,
                   name, lat_deg, lon_deg, alt_m, capability_json as capability,
                   content_sha256, denominator_inputs, first_seen_at
            from archive_stations
            where archive_station_id = %s
            """,
            (archive_station_id,),
        )
        return cur.fetchone()


def find_archive_stations_for_source(
    conn: Connection, source_id: str
) -> list[StoredArchiveStation]:
    """Every station description ever stored for this source.

    Args:
        conn: An open connection. Read-only; opens no transaction of its own.
        source_id: The source to list.

    Returns:
        The stations in first-seen order, empty when none was ever stored.

    Note:
        Several rows may describe one station, each a different published
        description of it. That is the point of the content key, and collapsing
        them here would hide exactly the change a denominator's history depends
        on.
    """
    with conn.cursor(row_factory=class_row(StoredArchiveStation)) as cur:
        cur.execute(
            """
            select archive_station_id, record_id, source_id, source_station_key,
                   name, lat_deg, lon_deg, alt_m, capability_json as capability,
                   content_sha256, denominator_inputs, first_seen_at
            from archive_stations
            where source_id = %s
            order by first_seen_at asc, archive_station_id asc
            """,
            (source_id,),
        )
        return cur.fetchall()


def count_denominator_inputs(conn: Connection, source_id: str) -> dict[str, int]:
    """How many stations Stage 16 can compute a denominator for, and how many not.

    Args:
        conn: An open connection. Read-only; opens no transaction of its own.
        source_id: The source to count.

    Returns:
        Every one of ``neither``, ``location_only`` and
        ``location_and_capability`` mapped to its count, including the zeroes.

    Note:
        **The zeroes are supplied deliberately.** A caller formatting a coverage
        line from this dictionary would otherwise print nothing for an absent
        key, and "no stations lacked a location" and "the question was not
        asked" would look identical on the page.

        EVALUATION.md's main methodological threat is selection bias, and a
        completeness ratio computed only over the stations we happened to have
        coordinates for — then reported as though it covered all of them — is
        that threat arriving through the back door. This is the number that
        stops it: published beside the ratio, never used to filter the rows.
    """
    counts = dict.fromkeys(("neither", "location_only", "location_and_capability"), 0)
    with conn.cursor(row_factory=class_row(_InputsCount)) as cur:
        cur.execute(
            """
            select denominator_inputs, count(*) as station_count
            from archive_stations
            where source_id = %s
            group by denominator_inputs
            """,
            (source_id,),
        )
        for row in cur.fetchall():
            counts[row.denominator_inputs] = row.station_count
    return counts
